version: 2

sources:
  - name: raw
    schema: raw_data_circle
    tables:
      - name: parcel
        identifier: raw_cc_parcel
      - name: sales
        identifier: raw_cc_sales
      - name: stock
        identifier: raw_cc_stock
